import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import Smallcard from '../components/Smallcard'
import MediumCard from '../components/MediumCard'
import styles from '../styles/Home.module.css'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'


export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">


      <Head>
        <title>Flowire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header />
      {/* Banner */}
      <Banner />
      {/* Main*/}
      <main className="max-w-7xl mx-auto px-8 sm:px-16" >
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Venues Nearby</h2>
          {/* Pull info from server */}
          {/* Have to add a key t the json file as a property */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <Smallcard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className=" text-4xl font-semibold py-8">Live Anywhere</h2>


          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>

        </section>

        <LargeCard
          img="https://links.papareact.com/4cj" title="Find your very own wedding planner" description="Wedding planner catalogue" buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  )
}


export async function getStaticProps() {
  const exploreData = await fetch('https://links.papareact.com/pyp').
    then(
      (res) => res.json()
    );

  const cardsData = await fetch('https://links.papareact.com/zp1').
    then(
      (res) => res.json()
    );

  return {
    props: {
      exploreData,
      cardsData
    }
  }

}